name: CI/CD using Github Actions

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt 
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply 
        run: terraform destroy -auto-approve

        
